# Generated by Django 4.1.4 on 2022-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=100)),
                ('imgurAlbum', models.CharField(default='', max_length=20)),
                ('albumAlias', models.CharField(default='', max_length=20)),
                ('googleDriveId', models.CharField(default='', max_length=100)),
                ('googleDriveUrl', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LineChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('text', models.TextField(blank=True)),
                ('fileId', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
